# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: Nanopore_WGS
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python~=3.7.1
  - bioconda::biopython
  - bioconda::samtools
  - bioconda::minimap2=2.22
  - bioconda::snpeff
  - bioconda::svdb
  - bioconda::sniffles
  - bioconda::bedtools
  - bioconda::mhcflurry
  - bioconda::vcftools
  - bioconda::bcftools
  - bioconda::nanofilt
  - bioconda::survivor
  - conda-forge::numpy
  - bioconda::cutesv
  - bioconda::vcfpy
  - bioconda::ensembl-vep=102.0
  - bioconda::fastqc
  - bioconda::parasail-python
  - pip
  - pip:
    - nanomonsv
    - svim
    